export const Home = (onNavigate) => {
  const HomeDiv = document.createElement('div');
  HomeDiv.className = 'cont_home';
  const buttonRegister = document.createElement('button');
  const buttonLogin = document.createElement('button');
  const divLogo = document.createElement('div');
  divLogo.className = 'logo';
  const letraLogo = document.createElement('h1');
  letraLogo.className = 'letraLogo';
  letraLogo.textContent = 'Lymusic';
  HomeDiv.appendChild(letraLogo);
  HomeDiv.appendChild(divLogo);
  const imagen = document.createElement('img');
  imagen.src = '../assets/img/sinFondo.png';
  imagen.alt = 'logoimagen';
  imagen.classList = 'logoimagen';
  divLogo.appendChild(imagen);
  const divBotones = document.createElement('div');
  divBotones.className = 'divBotones';
  buttonRegister.textContent = 'Register';
  buttonRegister.className = 'botonregistro';
  buttonLogin.textContent = 'Sign in';
  buttonLogin.className = 'botoniniciosesion';
  buttonRegister.addEventListener('click', () => onNavigate('/register'));
  buttonLogin.addEventListener('click', () => onNavigate('/login'));

  divBotones.appendChild(buttonRegister);
  divBotones.appendChild(buttonLogin);
  HomeDiv.appendChild(divBotones);
  return HomeDiv;
};
